version: 2

updates:

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'feat:'

  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'feat:'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: 'chore:'
