name: 'Docker Publish Description'

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/docker-description.yml

env:
  image_name: bjreplay/caddy-crowdsec-cf-dns

jobs:
  sync:
    name: Docker README.md Sync

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: DockerHub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository:  ${{ env.image_name }}
