name: 'GitHub Release'

on:
  push:
    tags:
      - 'v*.*.*'
      - '!v*.*.*-*'

permissions:
  contents: write

jobs:
  release:
    name: Create Release

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Release
        uses: softprops/action-gh-release@v2
        with:
          body: |
            [CHANGELOG](https://github.com/BJReplay/caddy-crowdsec-cf-dns/blob/master/CHANGELOG.md)